# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c168f4369ae0ff5096e85da94627dbc29be1cd7a8c5c8e33749a2369f0ee2153b4029b4e19ed8f4e6511fe0bdeeb7fe10fac3399326bf99ff9ceaad75be9d27f

test:
  secret_key_base: 8c56d1d626df9802e5d8fa95100d3fdc01bb75510bc822203b6cebbc24b24e1276f7c450242397dfc519fce4e5611973645af0488f99c450cd6d23b92123d34b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
